apiVersion: v1
kind: Service
metadata:
  name: scheduling-service
spec:
  selector:
    app: scheduling-microservice
  ports:
    - protocol: TCP
      port: 90
      targetPort: 90
  type: LoadBalancer
