apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: yourpassword  # Set your root password here
        - name: MYSQL_DATABASE
          value: scheduling_service
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'cp /config/init.sql /docker-entrypoint-initdb.d']
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: config-volume
        configMap:
          name: mysql-init-script
      - name: mysql-initdb
        emptyDir: {}
