apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: scheduling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mohammadtabbaby/schedulingservice
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: scheduling
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: LoadBalancer