apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-service-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: scheduling-microservice
  template:
    metadata:
      labels:
        app: scheduling-microservice
    spec:
      containers:
        - name: scheduling-microservice-container
          image: mohammadtabbaby/backend
          ports:
            - containerPort: 9002
