apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: scheduling
data:
  init.sql: |
    --
    -- Table structure for table `class_entity`
    --

    CREATE TABLE `class_entity` (
      `id` bigint(20) NOT NULL,
      `name` varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `class_entity`
    --

    INSERT INTO `class_entity` (`id`, `name`) VALUES
    (1, 'Master 1'),
    (2, 'Mastere 2');

    -- --------------------------------------------------------

    --
    -- Table structure for table `professor_entity`
    --

    CREATE TABLE `professor_entity` (
      `id` bigint(20) NOT NULL,
      `name` varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `professor_entity`
    --

    INSERT INTO `professor_entity` (`id`, `name`) VALUES
    (1, 'M. Adem'),
    (2, 'Mr. Rami'),
    (3, 'Mr. Hafedh');

    -- --------------------------------------------------------

    --
    -- Table structure for table `room_entity`
    --

    CREATE TABLE `room_entity` (
      `id` bigint(20) NOT NULL,
      `name` varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `room_entity`
    --

    INSERT INTO `room_entity` (`id`, `name`) VALUES
    (1, 'Salle 1'),
    (2, 'salle 0'),
    (3, 'Salle 13');

    -- --------------------------------------------------------

    --
    -- Table structure for table `subject_entity`
    --

    CREATE TABLE `subject_entity` (
      `id` bigint(20) NOT NULL,
      `name` varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `subject_entity`
    --

    INSERT INTO `subject_entity` (`id`, `name`) VALUES
    (1, 'Anglais'),
    (2, 'Automatisation'),
    (3, 'Culture Devops');

    -- --------------------------------------------------------

    --
    -- Table structure for table `timetable_entity`
    --

    CREATE TABLE `timetable_entity` (
      `id` bigint(20) NOT NULL,
      `class_id` bigint(20) DEFAULT NULL,
      `professor_id` bigint(20) DEFAULT NULL,
      `room_id` bigint(20) DEFAULT NULL,
      `subject_id` bigint(20) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `timetable_entity`
    --

    INSERT INTO `timetable_entity` (`id`, `class_id`, `professor_id`, `room_id`, `subject_id`) VALUES
    (1, 1, 1, 1, 1),
    (2, 1, 1, 1, 1),
    (3, 1, 1, 1, 1),
    (4, 2, 2, 3, 2),
    (5, 2, 3, 1, 3),
    (6, 2, 1, 3, 1);

    -- --------------------------------------------------------

    --
    -- Table structure for table `timetable_timeslots`
    --

    CREATE TABLE `timetable_timeslots` (
      `timetable_id` bigint(20) NOT NULL,
      `day` varchar(255) DEFAULT NULL,
      `end_time` varchar(255) DEFAULT NULL,
      `start_time` varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `timetable_timeslots`
    --

    INSERT INTO `timetable_timeslots` (`timetable_id`, `day`, `end_time`, `start_time`) VALUES
    (1, 'Friday', '10:00', '08:30'),
    (1, 'Wednesday', '11:40', '10:10'),
    (2, 'Monday', '11:40', '10:10'),
    (2, 'Tuesday', '10:00', '08:30'),
    (2, 'Tuesday', '11:40', '10:10'),
    (2, 'Monday', '10:00', '08:30'),
    (3, 'Tuesday', '10:00', '08:30'),
    (3, 'Monday', '11:40', '10:10'),
    (4, 'Monday', '10:00', '08:30'),
    (4, 'Tuesday', '11:40', '10:10'),
    (4, 'Monday', '11:40', '10:10'),
    (4, 'Tuesday', '10:00', '08:30'),
    (5, 'Wednesday', '11:40', '10:10'),
    (5, 'Wednesday', '10:00', '08:30'),
    (6, 'Friday', '10:00', '08:30');

    -- --------------------------------------------------------

    --
    -- Table structure for table `user`
    --

    CREATE TABLE `user` (
      `id` bigint(20) NOT NULL,
      `password` varchar(255) DEFAULT NULL,
      `username` varchar(255) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    --
    -- Dumping data for table `user`
    --

    INSERT INTO `user` (`id`, `password`, `username`) VALUES
    (1, 'admin', 'admin');
